apiVersion: v2
appVersion: 3.3.2
dependencies:
- alias: minio
  condition: minio.enabled
  name: minio
  repository: https://charts.min.io/
  version: 5.3.0
- alias: grafana-agent-operator
  condition: monitoring.selfMonitoring.grafanaAgent.installOperator
  name: grafana-agent-operator
  repository: https://grafana.github.io/helm-charts
  version: 0.5.0
- alias: rollout_operator
  condition: rollout_operator.enabled
  name: rollout-operator
  repository: https://grafana.github.io/helm-charts
  version: 0.21.0
description: Helm chart for Grafana Loki and Grafana Enterprise Logs supporting both
  simple, scalable and distributed modes.
home: https://grafana.github.io/helm-charts
icon: https://grafana.com/docs/loki/latest/logo_and_name.png
maintainers:
- name: trevorwhitney
- name: jeschkies
name: loki
sources:
- https://github.com/grafana/loki
- https://grafana.com/oss/loki/
- https://grafana.com/docs/loki/latest/
type: application
version: 6.24.0
