apiVersion: apps/v1
kind: Deployment
metadata:
  name: colosseum-agg
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: colosseum-agg
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"
      labels:
        app: colosseum-agg
    spec:
      containers:
      - name: colosseum-agg
        image: {{ .Values.global.image.registry }}/colosseum-agg:{{ .Values.monitoring.mode }}
        imagePullPolicy: Always
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        {{- if or (eq .Values.monitoring.mode "trace") ( eq .Values.monitoring.mode "profile") }}
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: {{ .Values.monitoring.tempo.ingest_url }}
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "service.name=colosseum-agg"
        - name: OTEL_EXPORTER_OTLP_INSECURE
          value: "true"
        - name: OTEL_METRICS_EXPORTER
          value: "none"
        - name: OTEL_SDK_DISABLED
          value: "false"
        - name: OTEL_LOGS_EXPORTER
          value: "none"
        {{- end }}
        {{- if eq .Values.monitoring.mode "profile" }}
        - name: PYROSCOPE_SERVER_ADDRESS
          value: {{ .Values.monitoring.pyroscope.url }}
        - name: PYROSCOPE_APPLICATION_NAME
          value: "colosseum-agg"
        {{- end }}
        - name: SPRING_CONFIG_LOCATION
          value: /config/application.yml
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config-volume
          mountPath: /config
          readOnly: true
      volumes:
      - name: config-volume
        configMap:
          name: colosseum-agg-config