apiVersion: v1
kind: ConfigMap
metadata:
  name: colosseum-agg-config
  namespace: {{ .Release.Namespace }}
data:
  application.yml: |
    spring:
      application:
        name: colosseum-agg
      data:
        redis:
          host: redis.{{- .Release.Namespace -}}.svc.cluster.local
          port: 6379
    springdoc:
      api-docs:
        path: /api-docs
    logging:
      config: classpath:logback-spring.xml
    management:
      endpoints:
        web:
          exposure:
            include: prometheus, health # /actuator/prometheus endpoint
      metrics:
        tags:
          application: app # add tag to each prometheus metric
        distribution:
          percentiles-histogram:
            http:
              server:
                requests: 'true'
          minimum-expected-value: # Publish fewer histogram buckets by clamping the range of expected values.
            http.server.requests: 5ms
          maximum-expected-value:
            http.server.requests: 1000ms
      server:
        port: 8080