apiVersion: apps/v1
kind: Deployment
metadata:
  name: colosseum-cms
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: colosseum-cms
  template:
    metadata:
      labels:
        app: colosseum-cms
    spec:
      containers:
      - name: colosseum-cms
        image: {{ .Values.global.image.registry }}/colosseum-cms:log
        imagePullPolicy: Always
        resources:
          requests:
            memory: "256Mi"
            cpu: "128m"
          limits:
            memory: "256Mi"
            cpu: "128m"
        env:
        - name: PORT
          value: "8082"
        - name: REDIS_HOST
          value: redis.{{- .Release.Namespace -}}.svc.cluster.local
        - name: REDIS_PORT
          value: "6379"
        ports:
        - containerPort: 8082