apiVersion: apps/v1
kind: Deployment
metadata:
  name: colosseum-nti
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: colosseum-nti
  template:
    metadata:
      labels:
        app: colosseum-nti
    spec:
      containers:
      - name: colosseum-nti
        image: {{ .Values.global.image.registry }}/colosseum-nti:log
        imagePullPolicy: Always
        resources:
          requests:
            memory: "256Mi"
            cpu: "128m"
          limits:
            memory: "256Mi"
            cpu: "128m"
        env:
        - name: PORT
          value: "8081"
        - name: REDIS_URL
          value: "redis://redis.{{- .Release.Namespace -}}.svc.cluster.local:6379"
        ports:
        - containerPort: 8081