apiVersion: apps/v1
kind: Deployment
metadata:
  name: promo-svc
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: promo-svc
  template:
    metadata:
      labels:
        app: promo-svc
    spec:
      containers:
      - name: promo-svc
        image: seongjumoon/promotion-service:log
        imagePullPolicy: Always
        resources:
          requests:
            memory: "256Mi"
            cpu: "128m"
          limits:
            memory: "256Mi"
            cpu: "128m"
        env:
        - name: PORT
          value: "8083"
        - name: REDIS_HOST
          value: redis.{{- .Release.Namespace -}}.svc.cluster.local
        - name: REDIS_PORT
          value: "6379"
        ports:
        - containerPort: 8083