apiVersion: v1
appVersion: RELEASE.2024-04-18T19-09-19Z
description: High Performance Object Storage
home: https://min.io
icon: https://min.io/resources/img/logo/MINIO_wordmark.png
keywords:
- minio
- storage
- object-storage
- s3
- cluster
maintainers:
- email: dev@minio.io
  name: MinIO, Inc
name: minio
sources:
- https://github.com/minio/minio
version: 5.3.0
