apiVersion: v2
appVersion: 1.10.0
dependencies:
- alias: agent
  condition: agent.enabled
  name: grafana-agent
  repository: https://grafana.github.io/helm-charts
  version: 0.25.0
- alias: alloy
  condition: alloy.enabled
  name: alloy
  repository: https://grafana.github.io/helm-charts
  version: 0.3.2
- alias: minio
  condition: minio.enabled
  name: minio
  repository: https://charts.min.io/
  version: 4.0.12
description: "\U0001F525 horizontally-scalable, highly-available, multi-tenant continuous
  profiling aggregation system"
home: https://grafana.com/oss/pyroscope/
name: pyroscope
sources:
- https://github.com/grafana/pyroscope
- https://github.com/grafana/pyroscope/tree/main/operations/pyroscope/helm/pyroscope
type: application
version: 1.10.0
