
global:
  image:
    registry: seongjumoon

monitoring:
  mode: log # log,trace,profile
  loki:
    url: http://grafana-stack-loki-gateway.monitoring.svc.cluster.local/
  tempo:
    url: http://grafana-stack-tempo.monitoring.svc.cluster.local:4318/
  pyroscope:
    url: http://grafana-stack-pyroscope.monitoring.svc.cluster.local:4040/